version: 2

models:
  - name: stg_events
    description: "One row per GA4 event (core fields only), filtered by _TABLE_SUFFIX in the model SQL."
    columns:
      - name: event_date
        description: "Event date as DATE."
        tests:
          - not_null

      - name: event_ts
        description: "Event timestamp as TIMESTAMP."
        tests:
          - not_null

      - name: event_name
        description: "GA4 event name (e.g., view_item, add_to_cart, purchase)."
        tests:
          - not_null

      - name: user_pseudo_id
        description: "Anonymous GA4 user identifier."
        tests:
          - not_null

  - name: stg_event_params
    description: "One row per GA4 event parameter (core fields only), filtered by _TABLE_SUFFIX in the model SQL."
    columns:
      - name: event_date
        description: "Event date as DATE."
        tests:
          - not_null

      - name: event_ts
        description: "Event timestamp as TIMESTAMP."
        tests:
          - not_null

      - name: event_name
        description: "GA4 event name (e.g., view_item, add_to_cart, purchase)."
        tests:
          - not_null

      - name: user_pseudo_id
        description: "Anonymous GA4 user identifier."
        tests:
          - not_null

  - name: stg_items
    description: "One row per GA4 event parameter (core fields only), filtered by _TABLE_SUFFIX in the model SQL."
    columns:
      - name: event_date
        description: "Event date as DATE."
        tests:
          - not_null

      - name: event_ts
        description: "Event timestamp as TIMESTAMP."
        tests:
          - not_null

      - name: event_name
        description: "GA4 event name (e.g., view_item, add_to_cart, purchase)."
        tests:
          - not_null

      - name: user_pseudo_id
        description: "Anonymous GA4 user identifier."
        tests:
          - not_null

